/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AnhStore.view;

import AnhStore.model.Product;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MyPC
 */
public class ListProductFrame extends javax.swing.JInternalFrame {

    DefaultTableModel model;
    ProductController dao;

    /**
     * Creates new form DanhSachSinhVienFrame
     */
    public ListProductFrame() {
        initComponents();
        dao = new ProductController();
        model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        setData(dao.getAllProducts());

    }

    private void setData(List<Product> products) {
        for (Product product : products) {
            model.addRow(new Object[]{product.getId(), product.getFullname(), product.getSoluong(), product.getGia()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        del = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        refesh = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();

        setTitle("Danh sách sinh viên");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Pro-name", "So luong", "Gia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                F5(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        del.setText("Xóa");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        edit.setText("Sửa");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        refesh.setText("Refesh");
        refesh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refeshActionPerformed(evt);
            }
        });

        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edit)
                .addGap(18, 18, 18)
                .addComponent(del)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refesh)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(del)
                    .addComponent(edit)
                    .addComponent(refesh)
                    .addComponent(btnAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
        int row = table.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(ListProductFrame.this, "Vui long chon product truoc", "Loi", JOptionPane.ERROR_MESSAGE);
        } else {
            int confirm = JOptionPane.showConfirmDialog(ListProductFrame.this, "Ban chac muon xoa?");

            if (confirm == JOptionPane.YES_OPTION) {
                int proId = Integer.valueOf(String.valueOf(table.getValueAt(row, 0)));
                dao.delProduct(proId);
                model.setRowCount(0);
                setData(dao.getAllProducts());
            }
        }
    }//GEN-LAST:event_delActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        int row = table.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(ListProductFrame.this, "Vui long chon product truoc", "Loi", JOptionPane.ERROR_MESSAGE);
        } else {
            int proId = Integer.valueOf(String.valueOf(table.getValueAt(row, 0)));
            JDesktopPane dk = getDesktopPane();
            EditProductFrame editframe = new EditProductFrame(proId);
            dk.add(editframe);
            editframe.setLocation(this.getWidth() / 2 - editframe.getWidth() / 2,
                                this.getHeight() / 2 - editframe.getHeight() / 2);
            editframe.setVisible(true);

        }
    }//GEN-LAST:event_editActionPerformed

    private void refeshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refeshActionPerformed
        // TODO add your handling code here:
        model.setRowCount(0);
        setData(dao.getAllProducts());
    }//GEN-LAST:event_refeshActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        JDesktopPane dk = getDesktopPane();
            AddProductFrame addframe = new AddProductFrame();
            dk.add(addframe);
            addframe.setLocation(this.getWidth() / 2 - addframe.getWidth() / 2,
                                this.getHeight() / 2 - addframe.getHeight() / 2);
            addframe.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void F5(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_F5
        // TODO add your handling code here:
       
    }//GEN-LAST:event_F5


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton del;
    private javax.swing.JButton edit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refesh;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
