/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lthdt.chuong3.dohoa.frame;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;
import lthdt.chuong3.coffeelogic.CoffeeShop;
import lthdt.chuong3.coffeelogic.Manager;

/**
 *
 * @author Fox0fNight
 */
public class MyCoffee extends javax.swing.JInternalFrame {

    Manager[] ma;

    /**
     * Creates new form MyCoffee
     */
    public MyCoffee() throws ParseException {
        initComponents();
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy", Locale.ENGLISH);
        CoffeeShop[] a = new CoffeeShop[]{new CoffeeShop("HighLand", "Le Loi"),
            new CoffeeShop("GongCha", "Nguyen Hue")};
        ma = new Manager[]{new Manager(a, 1000, "Le A", 0, df.parse("12-12-1999")),
            new Manager(new CoffeeShop[]{
                new CoffeeShop("hahah", "husudsdu")
            }, 2000, "Nguyen B", 1, df.parse("01-01-1991"))};
        for (int i = 0; i < ma.length; i++) {
            cbManager.addItem(ma[i].getHoten());
        }

        //mac dinh    
        DefaultTableModel model = (DefaultTableModel) tbCoffee.getModel();
        model.setRowCount(0);
        CoffeeShop[] shops = ma[0].getShops();
        for (int i = 0; i < shops.length; i++) {
            model.insertRow(model.getRowCount(),
                    new Object[]{model.getRowCount() + 1, shops[i].getName(), shops[i].getDiachi()}
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbManager = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCoffee = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);

        jLabel1.setText("ManagerName:");

        cbManager.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbManagerItemStateChanged(evt);
            }
        });
        cbManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbManagerActionPerformed(evt);
            }
        });

        tbCoffee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STT", "Ten", "Diachi"
            }
        ));
        jScrollPane1.setViewportView(tbCoffee);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbManager, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbManagerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbManagerActionPerformed

    private void cbManagerItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbManagerItemStateChanged
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbCoffee.getModel();
        model.setRowCount(0);
        int index = cbManager.getSelectedIndex();
        CoffeeShop[] shops = ma[index].getShops();
        for (int i = 0; i < shops.length; i++) {
            model.insertRow(model.getRowCount(),
                    new Object[]{model.getRowCount() + 1, shops[i].getName(), shops[i].getDiachi()}
            );
        }
    }//GEN-LAST:event_cbManagerItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbCoffee;
    // End of variables declaration//GEN-END:variables
}
